ReseauEntourage/entourage-job-back

- src/external-messages/external-messages.controller.ts
- src/external-messages/external-messages.service.ts
- src/mails/mails.service.ts
> [EN-6391] feat(form-contact): transfer to mail entreprise for offer subject

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/db/migrations/20240418105434-add-email-verification.js
- src/external-services/mailjet/mailjet.types.ts
- src/mails/mails.service.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.service.ts
- src/users/models/user.attributes.ts
- src/users/models/user.model.ts
- tests/users/users.e2e-spec.ts
Linked frontend PR: https://github.com/ReseauEntourage/entourage-job-front/pull/284
> [EN-7015] Feature/email verification flow

- src/auth/auth.controller.ts
- src/auth/guards/jwt.strategy.ts
- src/auth/guards/local.strategy.ts
- src/users-creation/dto/create-user.dto.ts
- tests/auth/auth.helper.ts
- tests/users/user.factory.ts
- tests/users/users.helper.ts
Frontend PR: https://github.com/ReseauEntourage/entourage-job-front/pull/286
> [EN-7056] feature: block unverified email login 

- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.service.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- src/users/users.service.ts
- tests/auth/auth.e2e-spec.ts
- tests/auth/auth.helper.ts
- tests/users/users.e2e-spec.ts
Frontend PR: https://github.com/ReseauEntourage/entourage-job-front/pull/287
- Small refactor in auth controller 
- Fixed circular dependencies in the worker module 
- Not returning a logged in user after registration - just a user - and fixing related tests 
- Set the isEmailVerified to false and send a new verification email if the user is changing his email address
> [EN-7032] Send verify email on email changes

- src/db/migrations/20240530162734-add-linkedin-link.js
- src/db/migrations/20240530162734-add-linkedin-url.js
- src/user-profiles/dto/create-candidate-user-profile.dto.ts
- src/user-profiles/dto/create-coach-user-profile.dto.ts
- src/user-profiles/dto/update-user-profile.pipe.ts
- src/user-profiles/models/user-profile.attributes.ts
- src/user-profiles/models/user-profile.model.ts
- src/user-profiles/user-profiles.types.ts
- src/user-profiles/user-profiles.utils.ts
- tests/users/users.e2e-spec.ts
Fontend PR: https://github.com/ReseauEntourage/entourage-job-front/pull/293
> [EN-7186] Linkedin Link

- src/cvs/cvs.controller.ts
- src/cvs/cvs.service.ts
- src/mails/mails.service.ts
Ne pas oublier de modifier le template mailjet en copiant le template Soumission de CV Coach et Candidat dans l'ancien (pour préserver le templateId)
> [EN-7139] Remove condition on the role

- .editorconfig
- src/auth/auth.controller.ts
- src/auth/auth.utils.ts
- src/cvs/cvs.controller.ts
- src/external-cvs/external-cvs.controller.ts
- src/main.ts
- src/opportunities/opportunities.controller.ts
- src/organizations/organizations.controller.ts
- src/user-profiles/user-profiles.controller.ts
- src/users-deletion/users-deletion.controller.ts
- src/users/users.controller.ts
- tests/auth/auth.e2e-spec.ts
- tests/cvs/cvs.e2e-spec.ts
- tests/external-cvs/external-cvs.e2e-spec.ts
- tests/messages/messages.e2e-spec.ts
- tests/opportunities/opportunities.e2e-spec.ts
- tests/organizations/organizations.e2e-spec.ts
- tests/read-documents/read-documents.e2e-spec.ts
- tests/users/users.e2e-spec.ts
Changement du header d'auth de toute l'app (Authorization: Token XXXXX vers Authorization: Bearer XXXXXX)
Et configuration des controller pour être correctement authentifié dans l'api doc
> [Swagger] Init API doc

- src/db/migrations/20240807082823-create-messaging.js
- src/messaging/messaging.service.ts
- Le content d'un message est maintenant un type TEXT pour pouvoir contenir plus de 255 caractères
- Modification de l'ordre des conversations
- Ajout de nouveaux attributs nécessaires
> Messaging - Conversations List

- src/user-profiles/user-profiles.service.ts
> fix(Messaging): report mail binder reporter reported was inverted

- src/messaging/messaging.controller.ts
- src/messaging/messaging.service.ts
- tests/messaging/messaging.e2e-spec.ts
- Conversation search is not case sensitive
- Fix get conversation order
> Messaging - Feedbacks

- src/external-databases/external-databases.service.ts
- src/external-services/salesforce/salesforce.service.ts
- src/external-services/salesforce/salesforce.types.ts
- src/external-services/salesforce/salesforce.utils.ts
- src/queues/consumers/work-queue.processor.ts
- src/queues/queues.types.ts
- src/users-creation/dto/create-user-registration.dto.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.service.ts
- tests/mocks.types.ts
- Refonte des casquettes 
- Creation de la structure asso si besoin 
- Envoi des infos prescripteur lors de la creation du compte prescripteur
- Link entre TS et Candidat lors de l'inscription du candidat par le TS
> [EN-7461] Envoi des infos prescripteur dans SF

- src/auth/auth.controller.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.service.ts
- Pour les coachs, candidats et prescripteurs, on envoie le mail de bienvenue apres la vérifications de l'email 
- Pour les candidats orientés par un presctipteur, on valide le mail automatiquement donc on envoi directement le mail de bienvenue
> [EN-8014] Envoi de l'email de bienvenue apres la vérification d'email 

- .github/workflows/main.yml
- README.md
- package.json
- src/db/migrations/20250423160127-add-utm.js
- src/users-creation/dto/create-user-registration.dto.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.module.ts
- src/users-creation/users-creation.service.ts
- src/utm/models/index.ts
- src/utm/models/utm.model.ts
- src/utm/utm.module.ts
- src/utm/utm.service.ts
[FRONT PR](https://github.com/ReseauEntourage/entourage-job-front/pull/452)
- Passage en engine node20
> [EN-8028] Store UTM in /registration

- src/user-profiles/user-profiles.controller.ts
- src/user-profiles/user-profiles.service.ts
- src/user-profiles/user-profiles.types.ts
**🗒️ Ticket Jira :** [EN-8054](https://entourage-asso.atlassian.net/browse/EN-8054)
**🚧 PR-Front :** [front/477](https://github.com/ReseauEntourage/entourage-job-front/pull/477)
Mise à jour du endpoint de recherche de profi pour pouvoir chercher par contactTypes
[EN-8054]: https://entourage-asso.atlassian.net/browse/EN-8054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EN-8054] Profile - Filtres du réseau d'entraide (by contactTypes)

- src/external-cvs/external-cvs.service.ts
- src/external-services/openai/openai.schemas.ts
**🗒️ Ticket Jira :** [EN-XXXX](https://entourage-asso.atlassian.net/browse/EN-XXXX)
**🚧 PR-Front :** [front/XXX](https://github.com/ReseauEntourage/entourage-job-front/pull/XXX)
> [EN-8295] Improvements onboarding IA

- Aptfile
- Dockerfile
- src/cvs/cvs.utils.ts
- src/external-cvs/external-cvs.controller.ts
- src/external-cvs/external-cvs.service.ts
- src/external-services/openai/openai.service.ts
**🗒️ Ticket Jira :** [EN-XXXX](https://entourage-asso.atlassian.net/browse/EN-XXXX)
**🚧 PR-Front :** [front/XXX](https://github.com/ReseauEntourage/entourage-job-front/pull/XXX)
> [FIX] Lib conversion PDF - PNG

- src/public-profiles/public-profiles.controller.ts
- src/public-profiles/public-profiles.services.ts
- src/users/users.service.ts
**🗒️ Ticket Jira :**
**🚧 PR-Front :**
Correction erreur 500 sur mauvais format url sur users/public-profiles/:candidateId quand candidateId n'est pas un uuid
> fix(PublicProfile): add check type candidateId

- src/user-profiles/user-profiles.controller.ts
- src/user-profiles/user-profiles.service.ts
**🗒️ Ticket Jira :** [[EN-XXXX](https://entourage-asso.atlassian.net/browse/EN-XXXX)](https://entourage-asso.atlassian.net/browse/EN-8362)
**🚧 PR-Front :** [[front/XXX](https://github.com/ReseauEntourage/entourage-job-front/pull/XXX)](https://github.com/ReseauEntourage/entourage-job-front/pull/502)
> [EN-8362] Profile completion

- src/app.module.ts
- src/companies/companies.controller.ts
- src/companies/companies.module.ts
- src/companies/companies.service.ts
- src/companies/dto/create-company.dto.ts
- src/companies/dto/create-company.pipe.ts
- src/companies/models/company-user.model.ts
- src/companies/models/company-user.service.ts
- src/companies/models/company-user.utils.ts
- src/companies/models/company.model.ts
- src/db/migrations/20250717094102-create-company.js
- src/external-databases/external-databases.service.ts
- src/external-services/salesforce/salesforce.service.ts
- src/external-services/salesforce/salesforce.types.ts
- src/external-services/salesforce/salesforce.utils.ts
- src/queues/consumers/work-queue.processor.ts
- src/queues/queues.types.ts
- src/users-creation/dto/create-user-refering.dto.ts
- src/users-creation/dto/create-user-registration.dto.ts
- src/users-creation/dto/create-user-registration.pipe.ts
- src/users-creation/users-creation.controller.ts
- src/users-creation/users-creation.module.ts
- src/users-creation/users-creation.service.ts
- src/users/models/user.include.ts
- src/users/models/user.model.ts
- src/users/users.types.ts
- tests/user-creation/user-creation.e2e-spec.ts
- tests/users/users.e2e-spec.ts
**🗒️ Ticket Jira :** [EN-7959](https://entourage-asso.atlassian.net/browse/EN-7959)
**🚧 PR-Front :** [front/XXX](https://github.com/ReseauEntourage/entourage-job-front/pull/XXX)
- Clean des "program" (et références 360/cdp)
[EN-7959]: https://entourage-asso.atlassian.net/browse/EN-7959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EN-7959] Company - Registration

- src/companies/companies.service.ts
**🗒️ Ticket Jira :** [EN-8376](https://entourage-asso.atlassian.net/browse/EN-8376)
**🚧 PR-Front :** [front/523](https://github.com/ReseauEntourage/entourage-job-front/pull/523)
[EN-8376]: https://entourage-asso.atlassian.net/browse/EN-8376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EN-8376] Company - Dashboard company collaborators

- src/db/migrations/20250829145254-remove-deprecated-cv-tables.js
**🗒️ Ticket Jira :** [EN-8126](https://entourage-asso.atlassian.net/browse/EN-8126)
[EN-8126]: https://entourage-asso.atlassian.net/browse/EN-8126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(migration): remove deprecated CV and Offers tables

- src/companies/companies.controller.ts
- src/companies/companies.includes.ts
- src/companies/companies.service.ts
- src/users/models/user.include.ts
**🗒️ Ticket Jira :** [EN-8522](https://entourage-asso.atlassian.net/browse/EN-8522)
[EN-8522]: https://entourage-asso.atlassian.net/browse/EN-8522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EN-8522] Fix 401 on collaborators fetch

- src/user-profiles/user-profiles.service.ts
**🗒️ Ticket Jira :** [EN-XXXX](https://entourage-asso.atlassian.net/browse/EN-XXXX)
**🚧 PR-Front :** [front/XXX](https://github.com/ReseauEntourage/entourage-job-front/pull/XXX)
sanitize jobname, fix occupations, improve query performance
> [EN-8415] - Company alerts - Retours 

- src/common/skills/models/skill.model.ts
- src/companies/companies.attributes.ts
- src/db/migrations/20250926142914-add-skills-timestamps.js
- src/user-profiles/user-profiles.service.ts
**🗒️ Ticket Jira :** [EN-8489](https://entourage-asso.atlassian.net/browse/EN-8489)
**🚧 PR-Front :** [front/547](https://github.com/ReseauEntourage/entourage-job-front/pull/547)
- Ajout d'un createdAt / updatedAt au Skills
[EN-8489]: https://entourage-asso.atlassian.net/browse/EN-8489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EN-8489] UserProfile - Skill selection
